unit ulang_consts;

interface

uses
  System.Classes;

const
  clEXPORT_SELECTED_LANGUAGE = 0;
  clCANCEL = 1;
  clOK = 2;
  clSAVE = 3;
  clCHANGE = 4;
  clGENERAL = 5;
  clLANGUAGES = 6;
  clCONFIGURATION = 7;
  clDIRECTORIES = 8;
  clDIRECTORY = 9;
  clCONTROLLERS = 10;
  clCONTROLLER = 11;
  clVFILE = 12;
  clCONFIGURATE_CONTROLS_INPUT = 13;
  clCONFIGURATE_CONTROLS = 14;
  clPLAYERS = 15;
  clIN_GAME = 16;
  clFRONTEND = 17;
  clPLAY = 18;
  clQUIT_DEmuFM = 19;
  clMOVE_UP = 20;
  clMOVE_DOWN = 21;
  clMOVE_LEFT = 22;
  clMOVE_RIGHT = 23;
  clSHOW_CONFIGURATION = 24;
  clSHOW_CONFIGURATE_CONTROLS = 25;
  clSHOW_CONFIGURATE_DISPLAY = 26;
  clSHOW_INFORMATION = 27;
  clSHOW_HIDE_TIME_PLAY = 28;
  clCHOOSE_PLATFORM_EMULATION = 29;
  clRESET_GAME = 30;
  clSERVICE = 31;
  clFAST_FPS = 32;
  clSLOW_FPS = 33;
  clLEAVE_GAME = 34;
  clPAUSE_GAME = 35;
  clFULLSCREEN = 36;
  clTAKE_SNAPSHOT_PNG_JPG = 37;
  clPLAYER_1_SAVE_STATE = 38;
  clPLAYER_1_LOAD_STATE = 39;
  clPLAYER_2_SAVE_STATE = 40;
  clPLAYER_2_LOAD_STATE = 41;
  clEMULATION_PLATFORM = 42;
  clKEYBOARD = 43;
  clPROFILE = 44;
  clLOAD = 45;
  clPLAYER = 46;
  clUP = 47;
  clDOWN = 48;
  clLEFT = 49;
  clRIGHT = 50;
  clBUTTON = 51;
  clCOIN = 52;
  clSTART = 53;
  clJOYSTICK_INFORMATION = 54;
  clVTYPE = 55;
  clBUTTONS = 56;
  clVENDOR = 57;
  clPRODUCT = 58;
  clNUMBER = 59;
  clSERIAL_NUMBER = 60;
  clPRODUCT_NUMBER = 61;
  clNAME = 62;
  clFIND_GAME = 63;
  clNONE = 64;
  clELLINIKA = 65;
  clSPAIN = 66;
  clRUSSIAN = 67;
  clENGLISH = 68;
  clFRANCAIS = 69;
  clGERMAN = 70;
  clBRAZIL = 71;
  clITALIAN = 72;
  clGRAPHICS = 73;
  clSOUND = 74;
  clMEDIA = 75;
  clmEXPORT = 76;
  clEXPORT_COMPATIBILITY_LIST = 77;
  clSELECT_GRAPHICS_DRIVER = 78;
  clSELECTED_GRAPHICS_DRIVER = 79;
  clWINDOW_STATE = 80;
  clWINDOW  = 81;
  clWINDOW_MODE = 82;
  clFULLSCREEN_MODE = 83;
  clCENTER_IN_DESKTOP = 84;
  clWINDOW_SIZE = 85;
  clORIGINAL = 86;
  clmWIDTH = 87;
  clmHEIGHT = 88;
  clSHOW_BEZELS = 89;
  clENABLE_SOUND = 90;
  clADD = 91;
  clINFORMATION = 92;
  clCREATED_BY = 93;
  clCREATOR = 94;
  clPROGRAMMING_LANGUAGE = 95;
  clVERSION = 96;
  clINFO_MEMO = 97;

  // PopUP
  pop1 = 1; // Click here to edit the selected keys for the player 2 actions.
  pop2 = 2; // Set a key to start a selected game. Default key is (ENTER).
  pop3 = 3; // Set a key to move up the selector. Default key is (UP).
  pop4 = 4; // Set a key to move down the selector. Default key is (DOWN).
  pop5 = 5; // Set a key to move left the selector. Default key is (LEFT).
  pop6 = 6; // Set a key to move right the selector. Default key is (Right).
  pop7 = 7; // Set a key to display the configuration panel. Default key is (C).
  pop8 = 8; // Set a key to display the controls configuration panel. Default key is (X).
  pop9 = 9; // Set a key to display the video configuration panel. Default key is (V).
  pop10 = 10; // Set a key to display the information about DSP_FM. Default key is (I).
  pop11 = 11; // Set a key to hide or show the total time you play for the selected game. Default key is (T).
  pop12 = 12; // Set a key to display the emulators panel. Default key is (E).
  pop13 = 13; // Click here to edit the selected keys for frontend.
  pop14 = 14; // Here you can see and edit fields that have to do with the frontend
  pop15 = 15; // Set a key to reset a game. Default key is (F4).
  pop16 = 16; // Set a key to go to the service of the game. Default key is (F1).
  pop17 = 17; // Set a key to set the game in fastest FPS and Normal FPS. Default key is (F2).
  pop18 = 18; // Set a key to lower FPS to 50%, 25% and back to normal. Default key is (F3).
  pop19 = 19; // Set a key to exit game. Default key is (ESC).
  pop20 = 20; // Set a key to pause game. Default key is (P).
  pop21 = 21; // Set a key to set the game in fullscreen or in window form. Default key is (F6).
  pop22 = 22; // Set a key to take a picture snapshot of the game. Default key is (F12).
  pop23 = 23; // Set a key to save a game state for player 1. Default key is (F7).
  pop24 = 24; // Set a key to load a saved game state for player 1. Default key is (F8).
  pop25 = 25; // Set a key to save a game state for player 2. Default key is (F9).
  pop26 = 26; // Set a key to load a saved game state for player 2. Default key is (F10).
  pop27 = 27; // Click here to edit the selected keys for the in game action.
  pop28 = 28; // Here you can see and edit fields that have to do when the game starts.
  pop29 = 29; // Select from the list the emulator that you want to edit the controllers.
  pop30 = 30; // Select the controller from the list.
  pop31 = 31; // Select profile of the saved controller. If the joystick of the profile is not active then
  // you get the default keyboard schema
  pop32 = 32; // Here you can see and edit fields of the first player action keys.
  pop33 = 33; // Here you can see and edit fields of the second player action keys.
  pop34 = 34; // Here you can see and edit fields of the third player action keys.
  pop35 = 35; // Here you can see and edit fields of the fourth player action keys.
  pop36 = 36; // Press to see information about the selected joystick.
  pop37 = 37; // Set a key for the move up action for player 1. Default key is ().
  pop38 = 38; // Set a key for the move down action for player 1. Default key is ().
  pop39 = 39; // Set a key for the move left action for player 1. Default key is ().
  pop40 = 40; // Set a key for the move right action for player 1. Default key is ().
  pop41 = 41; // Set a key for the button 1 action for player 1. Default key is ().
  pop42 = 42; // Set a key for the button 2 action for player 1. Default key is ().
  pop43 = 43; // Set a key for the button 3 action for player 1. Default key is ().
  pop44 = 44; // Set a key for the button 4 action for player 1. Default key is ().
  pop45 = 45; // Set a key for the button 5 action for player 1. Default key is ().
  pop46 = 46; // Set a key for the button 6 action for player 1. Default key is ().
  pop47 = 47; // Set a key for the coin action for player 1. Default key is ().
  pop48 = 48; // Set a key for the start action for player 1. Default key is ().
  pop49 = 49; // Click here to edit the selected keys for the player 1 actions.
  pop50 = 50; // Set a key for the move up action for player 2. Default key is ().
  pop51 = 51; // Set a key for the move down action for player 2. Default key is ().
  pop52 = 52; // Set a key for the move left action for player 2. Default key is ().
  pop53 = 53; // Set a key for the move right action for player 2. Default key is ().
  pop54 = 54; // Set a key for the button 1 action for player 2. Default key is ().
  pop55 = 55; // Set a key for the button 2 action for player 2. Default key is ().
  pop56 = 56; // Set a key for the button 3 action for player 2. Default key is ().
  pop57 = 57; // Set a key for the button 4 action for player 2. Default key is ().
  pop58 = 58; // Set a key for the button 5 action for player 2. Default key is ().
  pop59 = 59; // Set a key for the button 6 action for player 2. Default key is ().
  pop60 = 60; // Set a key for the coin action for player 2. Default key is ().
  pop61 = 61; // Set a key for the start action for player 2. Default key is ().
  pop62 = 62; // Click here to edit the selected keys for the player 2 actions.
  pop63 = 63; // Set a key for the move up action for player 3. Default key is ().
  pop64 = 64; // Set a key for the move down action for player 3. Default key is ().
  pop65 = 65; // Set a key for the move left action for player 3. Default key is ().
  pop66 = 66; // Set a key for the move right action for player 3. Default key is ().
  pop67 = 67; // Set a key for the button 1 action for player 3. Default key is ().
  pop68 = 68; // Set a key for the button 2 action for player 3. Default key is ().
  pop69 = 69; // Set a key for the button 3 action for player 3. Default key is ().
  pop70 = 70; // Set a key for the button 4 action for player 3. Default key is ().
  pop71 = 71; // Set a key for the button 5 action for player 3. Default key is ().
  pop72 = 72; // Set a key for the button 6 action for player 3. Default key is ().
  pop73 = 73; // Set a key for the coin action for player 3. Default key is ().
  pop74 = 74; // Set a key for the start action for player 3. Default key is ().
  pop75 = 75; // Click here to edit the selected keys for the player 3 actions.
  pop76 = 76; // Set a key for the move up action for player 4. Default key is ().
  pop77 = 77; // Set a key for the move down action for player 4. Default key is ().
  pop78 = 78; // Set a key for the move left action for player 4. Default key is ().
  pop79 = 79; // Set a key for the move right action for player 4. Default key is ().
  pop80 = 80; // Set a key for the button 1 action for player 4. Default key is ().
  pop81 = 81; // Set a key for the button 2 action for player 4. Default key is ().
  pop82 = 82; //  Set a key for the button 3 action for player 4. Default key is ().
  pop83 = 83; //  Set a key for the button 4 action for player 4. Default key is ().
  pop84 = 84; // Set a key for the button 5 action for player 4. Default key is ().
  pop85 = 85; // Set a key for the button 6 action for player 4. Default key is ().
  pop86 = 86; //  Set a key for the coin action for player 4. Default key is ().
  pop87 = 87; //  Set a key for the start action for player 4. Default key is ().
  pop88 = 88; //  Click here to edit the selected keys for the player 4 actions.
  pop89 = 89; // Press to load the selected profile.
  pop90 = 90; // Press to save the selected profile.
  pop91 = 91; //



implementation

end.
