
unit uDataModule;

interface

uses
  System.SysUtils, System.Classes, FireDAC.Stan.Intf, FireDAC.Stan.Option,
  FireDAC.Stan.Param, FireDAC.Stan.Error, FireDAC.DatS, FireDAC.Phys.Intf,
  FireDAC.DApt.Intf, FireDAC.UI.Intf, FireDAC.Stan.Def, FireDAC.Stan.Pool,
  FireDAC.Stan.Async, FireDAC.Phys, FireDAC.Phys.SQLite, FireDAC.Phys.SQLiteDef,
  FireDAC.Stan.ExprFuncs, FireDAC.Phys.SQLiteWrapper.Stat, FireDAC.FMXUI.Wait,
  Data.DB, FireDAC.Comp.Client, FireDAC.Comp.DataSet, FireDAC.DApt,
  Data.Bind.Components, Data.Bind.DBScope;

type
  Tdm = class(TDataModule)
    fdconn: TFDConnection;
    query: TFDQuery;
    tConfig: TFDTable;
    tArcade: TFDTable;
    tArcadeConfig: TFDTable;
    tArcadeTGDB: TFDTable;
    tArcadeTGDBImages: TFDTable;
    tTGDBDevelopers: TFDTable;
    tArcadenum: TFDAutoIncField;
    tArcaderom: TWideMemoField;
    tArcadename: TWideMemoField;
    tArcadeyear: TWideMemoField;
    tArcademanufactor: TWideMemoField;
    tArcaderom_path: TWideMemoField;
    tArcaderom_global_path: TWideMemoField;
    tArcadeexe_num: TIntegerField;
    tArcadestate: TWideMemoField;
    tArcadestate_icon: TIntegerField;
    tArcadestate_desc: TWideMemoField;
    tArcadestate_date: TWideMemoField;
    tArcadehiscore: TIntegerField;
    tArcadetotal_time: TIntegerField;
    tArcadeTGDBid: TIntegerField;
    tArcadeTGDBtitle: TWideMemoField;
    tArcadeTGDBrelease_date: TWideMemoField;
    tArcadeTGDBplatform_id: TWideMemoField;
    tArcadeTGDBplayers: TWideMemoField;
    tArcadeTGDBoverview: TWideMemoField;
    tArcadeTGDBlast_updated: TWideMemoField;
    tArcadeTGDBrating: TWideMemoField;
    tArcadeTGDBcoop: TWideMemoField;
    tArcadeTGDByoutube: TWideMemoField;
    tArcadeTGDBos: TWideMemoField;
    tArcadeTGDBprocessor: TWideMemoField;
    tArcadeTGDBram: TWideMemoField;
    tArcadeTGDBhdd: TWideMemoField;
    tArcadeTGDBvideo: TWideMemoField;
    tArcadeTGDBsound: TWideMemoField;
    tArcadeTGDBdevelopers: TWideMemoField;
    tArcadeTGDBgenres: TWideMemoField;
    tArcadeTGDBpublishers: TWideMemoField;
    tArcadeTGDBalternates: TWideMemoField;
    tArcadeTGDBrom: TWideMemoField;
    tTGDBGenres: TFDTable;
    tTGDBPlatforms: TFDTable;
    tTGDBPublishers: TFDTable;
    tConfigEmus: TFDTable;
    tConfigEmusnum: TFDAutoIncField;
    tConfigEmusemulator: TWideMemoField;
    tConfigEmusbox_art: TWideMemoField;
    tConfigEmussnapshot: TWideMemoField;
    tConfigEmusvideo: TWideMemoField;
    tConfigEmusmanual: TWideMemoField;
    tConfigEmusbezels: TWideMemoField;
    tGamepad: TFDTable;
    tGamepadnum: TFDAutoIncField;
    tGamepadgname: TWideMemoField;
    tGamepadname: TWideMemoField;
    tGamepadgtype: TWideMemoField;
    tGamepadserial: TWideMemoField;
    tGamepadbuttons: TWideMemoField;
    tGamepadguid: TWideMemoField;
    tGamepadvendor: TWideMemoField;
    tGamepadproduct: TWideMemoField;
    tGamepadproduct_version: TWideMemoField;
    tGamepadhat_up: TIntegerField;
    tGamepadhat_down: TIntegerField;
    tGamepadhat_left: TIntegerField;
    tGamepadhat_right: TIntegerField;
    tGamepadleft_x_plus: TIntegerField;
    tGamepadleft_x_minus: TIntegerField;
    tGamepadleft_y_plus: TIntegerField;
    tGamepadleft_y_minus: TIntegerField;
    tGamepadright_x_plus: TIntegerField;
    tGamepadright_x_minus: TIntegerField;
    tGamepadright_y_plus: TIntegerField;
    tGamepadright_y_minus: TIntegerField;
    tGamepadleft_deadzone: TIntegerField;
    tGamepadright_deadzone: TIntegerField;
    tGamepadb0: TIntegerField;
    tGamepadb1: TIntegerField;
    tGamepadb2: TIntegerField;
    tGamepadb3: TIntegerField;
    tGamepadb4: TIntegerField;
    tGamepadb5: TIntegerField;
    tGamepadb6: TIntegerField;
    tGamepadb7: TIntegerField;
    tGamepadb8: TIntegerField;
    tGamepadb9: TIntegerField;
    tGamepadb10: TIntegerField;
    tGamepadb11: TIntegerField;
    tGamepadb12: TIntegerField;
    tGamepadb13: TIntegerField;
    tGamepadb14: TIntegerField;
    tGamepadb15: TIntegerField;
    tGamepadcoin: TIntegerField;
    tGamepadstart: TIntegerField;
    tGamepadtrigger_left: TIntegerField;
    tGamepadtrigger_right: TIntegerField;
    tGamepadleft: TIntegerField;
    tGamepadright: TIntegerField;
    tJoystick: TFDTable;
    tJoysticknum: TFDAutoIncField;
    tJoystickjname: TIntegerField;
    tJoystickname: TWideMemoField;
    tJoystickplayer: TIntegerField;
    tJoystickjtype: TWideMemoField;
    tJoystickbuttons: TIntegerField;
    tJoystickguid: TWideMemoField;
    tJoystickvendor: TWideMemoField;
    tJoystickproduct: TWideMemoField;
    tJoystickproduct_version: TWideMemoField;
    tJoystickserial: TWideMemoField;
    tJoystickaxis_x_plus: TIntegerField;
    tJoystickaxis_x_minus: TIntegerField;
    tJoystickaxis_y_plus: TIntegerField;
    tJoystickaxis_y_minus: TIntegerField;
    tJoystickdeadzone_x: TIntegerField;
    tJoystickdeadzone_y: TIntegerField;
    tJoystickbutton0: TIntegerField;
    tJoystickbutton1: TIntegerField;
    tJoystickbutton2: TIntegerField;
    tJoystickbutton3: TIntegerField;
    tJoystickbutton4: TIntegerField;
    tJoystickbutton5: TIntegerField;
    tJoystickbutton6: TIntegerField;
    tJoystickbutton7: TIntegerField;
    tJoystickbutton8: TIntegerField;
    tJoystickbutton9: TIntegerField;
    tJoystickbutton10: TIntegerField;
    tJoystickbutton11: TIntegerField;
    tJoystickbutton12: TIntegerField;
    tJoystickbutton13: TIntegerField;
    tJoystickbutton14: TIntegerField;
    tJoystickbutton15: TIntegerField;
    tJoystickstart: TIntegerField;
    tJoystickcoin: TIntegerField;
    tKeyboard: TFDTable;
    tKeyboardFrontend: TFDTable;
    tKeyboardFrontendnum: TFDAutoIncField;
    tKeyboardFrontendname: TWideMemoField;
    tKeyboardFrontendquit_dspfm: TWideMemoField;
    tKeyboardFrontendplay: TWideMemoField;
    tKeyboardFrontendmove_up: TWideMemoField;
    tKeyboardFrontendmove_down: TWideMemoField;
    tKeyboardFrontendmove_left: TWideMemoField;
    tKeyboardFrontendmove_right: TWideMemoField;
    tKeyboardFrontendshow_configuration: TWideMemoField;
    tKeyboardFrontendshow_display: TWideMemoField;
    tKeyboardFrontendshow_controls: TWideMemoField;
    tKeyboardFrontendshow_information: TWideMemoField;
    tKeyboardFrontendshow_hide_time_game: TWideMemoField;
    tKeyboardFrontendplatform_emulators: TWideMemoField;
    tKeyboardInGame: TFDTable;
    tLanguage: TFDTable;
    tLanguagePop: TFDTable;
    tKeyboardnum: TFDAutoIncField;
    tKeyboardkey_up: TIntegerField;
    tKeyboardkey_down: TIntegerField;
    tKeyboardkey_left: TIntegerField;
    tKeyboardkey_right: TIntegerField;
    tKeyboardkey_b0: TIntegerField;
    tKeyboardkey_b1: TIntegerField;
    tKeyboardkey_b2: TIntegerField;
    tKeyboardkey_b3: TIntegerField;
    tKeyboardkey_b4: TIntegerField;
    tKeyboardkey_b5: TIntegerField;
    tKeyboardkey_coin: TIntegerField;
    tKeyboardkey_start: TIntegerField;
    tKeyboardInGamenum: TFDAutoIncField;
    tKeyboardInGamename: TWideMemoField;
    tKeyboardInGameleave_game: TIntegerField;
    tKeyboardInGamepause_game: TIntegerField;
    tKeyboardInGamefullscreen_game: TIntegerField;
    tKeyboardInGameservice: TIntegerField;
    tKeyboardInGamefastest: TIntegerField;
    tKeyboardInGameslow: TIntegerField;
    tKeyboardInGamereset: TIntegerField;
    tKeyboardInGamesave_snap_player_1: TIntegerField;
    tKeyboardInGamesave_snap_player_2: TIntegerField;
    tKeyboardInGameload_snap_player_1: TIntegerField;
    tKeyboardInGameload_snap_player_2: TIntegerField;
    tKeyboardInGamesnapshot: TIntegerField;
    tKeyboardInGameshow_info: TIntegerField;
    tNes: TFDTable;
    tNes_Config: TFDTable;
    IntegerField5: TIntegerField;
    IntegerField6: TIntegerField;
    IntegerField7: TIntegerField;
    IntegerField8: TIntegerField;
    IntegerField9: TIntegerField;
    IntegerField10: TIntegerField;
    IntegerField11: TIntegerField;
    IntegerField12: TIntegerField;
    tNesMedia: TFDTable;
    tNesTGDB: TFDTable;
    tNesTGDBImages: TFDTable;
    IntegerField14: TIntegerField;
    IntegerField15: TIntegerField;
    WideMemoField35: TWideMemoField;
    WideMemoField36: TWideMemoField;
    WideMemoField37: TWideMemoField;
    WideMemoField38: TWideMemoField;
    WideMemoField39: TWideMemoField;
    tNesnum: TFDAutoIncField;
    tNesrom: TWideMemoField;
    tNesrom_path: TWideMemoField;
    tNesstate: TWideMemoField;
    tNesstate_icon: TIntegerField;
    tNesstate_desc: TWideMemoField;
    tNestotal_time: TIntegerField;
    tNesMedianum: TFDAutoIncField;
    tNesMediarom: TWideMemoField;
    tNesMediabox_art: TWideMemoField;
    tNesMediasnapshots: TWideMemoField;
    tNesMediamanuals: TWideMemoField;
    tNesMediavideos: TWideMemoField;
    tNesTGDBnum: TFDAutoIncField;
    tNesTGDBid: TIntegerField;
    tNesTGDBtitle: TWideMemoField;
    tNesTGDBrelease_date: TWideMemoField;
    tNesTGDBplatform_id: TWideMemoField;
    tNesTGDBplayers: TWideMemoField;
    tNesTGDBoverview: TWideMemoField;
    tNesTGDBlast_updated: TWideMemoField;
    tNesTGDBrating: TWideMemoField;
    tNesTGDBcoop: TWideMemoField;
    tNesTGDByoutube: TWideMemoField;
    tNesTGDBos: TWideMemoField;
    tNesTGDBprocessor: TWideMemoField;
    tNesTGDBram: TWideMemoField;
    tNesTGDBhdd: TWideMemoField;
    tNesTGDBvideo: TWideMemoField;
    tNesTGDBsound: TWideMemoField;
    tNesTGDBdevelopers: TWideMemoField;
    tNesTGDBgenres: TWideMemoField;
    tNesTGDBpublishers: TWideMemoField;
    tNesTGDBalternates: TWideMemoField;
    tNesTGDBbox_art_original: TWideMemoField;
    tNesTGDBbox_art_small: TWideMemoField;
    tNesTGDBbox_art_thumb: TWideMemoField;
    tNesTGDBbox_art_cropped: TWideMemoField;
    tNesTGDBbox_art_medium: TWideMemoField;
    tNesTGDBbox_art_large: TWideMemoField;
    tNesTGDBpic_1: TWideMemoField;
    tNesTGDBpic_1_ext: TWideMemoField;
    tNesTGDBrom: TWideMemoField;
    tPlayers: TFDTable;
    tPlayersnum: TFDAutoIncField;
    tPlayersname: TWideMemoField;
    tPlayersplayer: TIntegerField;
    tPlayerskey: TIntegerField;
    tPlayersjoy: TIntegerField;
    tPlayersgpd: TIntegerField;
    tPlayersplatform: TWideMemoField;
    tPlayerskey_map_num: TIntegerField;
    tPlayersselected: TIntegerField;
    tPlayersactive: TIntegerField;
    tLanguagenum: TFDAutoIncField;
    tLanguageellinika: TWideMemoField;
    tLanguagespain: TWideMemoField;
    tLanguagerussian: TWideMemoField;
    tLanguageenglish: TWideMemoField;
    tLanguagefrancais: TWideMemoField;
    tLanguagegerman: TWideMemoField;
    tLanguagebrazil: TWideMemoField;
    tLanguageitalian: TWideMemoField;
    tLanguagePopnum: TFDAutoIncField;
    tLanguagePopellinika: TWideMemoField;
    tLanguagePopcatallan: TWideMemoField;
    tLanguagePopcastellano: TWideMemoField;
    tLanguagePopenglish: TWideMemoField;
    tLanguagePopfrancais: TWideMemoField;
    tLanguagePopgerman: TWideMemoField;
    tLanguagePopbrazil: TWideMemoField;
    tLanguagePopitalian: TWideMemoField;
    tKeyboardplayer: TIntegerField;
    tKeyboardemulator: TWideMemoField;
    bsDBArcade: TBindSourceDB;
    bsDBArcadeConfig: TBindSourceDB;
    bsDBArcadeTGDB: TBindSourceDB;
    bsDBArcadeTGDBImages: TBindSourceDB;
    bsDBTGDBDevelopers: TBindSourceDB;
    bsDBTGDBGenres: TBindSourceDB;
    bsDBTGDBPublishers: TBindSourceDB;
    tArcadeConfignum: TIntegerField;
    tArcadeConfigfullscreen: TIntegerField;
    tArcadeConfigfull_x: TIntegerField;
    tArcadeConfigfull_y: TIntegerField;
    tArcadeConfigbezels: TIntegerField;
    tArcadeConfigwin_center: TIntegerField;
    tArcadeConfigwin_size: TIntegerField;
    tArcadeConfigsound: TIntegerField;
    tArcadeTGDBImagesid: TIntegerField;
    tArcadeTGDBImagesrom: TWideMemoField;
    tArcadeTGDBImagesimg_type: TWideMemoField;
    tArcadeTGDBImagesside: TWideMemoField;
    tArcadeTGDBImagesfilename: TWideMemoField;
    tArcadeTGDBImagesresolution: TWideMemoField;
    tArcadeTGDBImagespath: TWideMemoField;
    tConfigfirstrun: TIntegerField;
    tConfigcurrent_emu: TWideMemoField;
    tConfigprj_name: TWideMemoField;
    tConfigprj_path: TWideMemoField;
    tConfigprj_version: TWideMemoField;
    tConfigprj_images_main: TWideMemoField;
    tConfigprj_images_bar: TWideMemoField;
    tConfigprj_images_config: TWideMemoField;
    tConfigprj_images_flags: TWideMemoField;
    tConfigprj_images_controls: TWideMemoField;
    tConfigprj_media: TWideMemoField;
    tConfigprj_export: TWideMemoField;
    tConfigprj_themes: TWideMemoField;
    tConfigprj_sounds: TWideMemoField;
    tConfigprj_fonts: TWideMemoField;
    tConfigprj_temp: TWideMemoField;
    tConfigprj_kind: TWideMemoField;
    tConfiglang: TIntegerField;
    tConfighiscore: TWideMemoField;
    tConfignvram: TWideMemoField;
    tConfigqsnapshot: TWideMemoField;
    tConfigsamples: TWideMemoField;
    tConfigsound: TIntegerField;
    tConfigvideo: TIntegerField;
    tConfigscraper: TWideMemoField;
    ingame: TFDTable;
    ingameshowFPS: TIntegerField;
    tTGDBDevelopersid: TIntegerField;
    tTGDBDevelopersname: TWideMemoField;
    tTGDBGenresid: TIntegerField;
    tTGDBGenresname: TWideMemoField;
    tTGDBPublishersid: TIntegerField;
    tTGDBPublishersname: TWideMemoField;
    tTGDBPlatformsid: TIntegerField;
    tTGDBPlatformsname: TWideMemoField;
    tTGDBPlatformsalias: TWideMemoField;
    tTGDBPlatformsicon: TBlobField;
    tTGDBPlatformsconsole: TWideMemoField;
    tTGDBPlatformscontroller: TWideMemoField;
    tTGDBPlatformsdeveloper: TWideMemoField;
    tTGDBPlatformsmanufactor: TWideMemoField;
    tTGDBPlatformsmedia: TWideMemoField;
    tTGDBPlatformscpu: TWideMemoField;
    tTGDBPlatformsmemory: TWideMemoField;
    tTGDBPlatformsgraphics: TWideMemoField;
    tTGDBPlatformssound: TWideMemoField;
    tTGDBPlatformsmax_controllers: TWideMemoField;
    tTGDBPlatformsdisplay: TWideMemoField;
    tTGDBPlatformsoverview: TWideMemoField;
    tTGDBPlatformsyoutube: TWideMemoField;
    tArcadeTGDBImagesurl_path: TWideMemoField;
    tArcadeConfigselect_cover: TWideMemoField;
    tArcadeConfigfrontend_type: TWideMemoField;
    tArcadeplay_times: TIntegerField;
    tArcadestate_status: TWideMemoField;
    tArcadelast_played: TWideMemoField;
    tArcadevideo_rendering: TWideMemoField;
    tArcadeConfigvideo_rendering: TWideMemoField;
    procedure DataModuleCreate(Sender: TObject);
    procedure DataModuleDestroy(Sender: TObject);
  private
    { Private declarations }
  public
    { Public declarations }
  end;

var
  dm: Tdm;

implementation

{%CLASSGROUP 'FMX.Controls.TControl'}

{$R *.dfm}

procedure Tdm.DataModuleCreate(Sender: TObject);
begin
  tArcade.IndexFieldNames := 'rom';
  tArcadeTGDB.IndexFieldNames := 'rom';
  tArcadeTGDBImages.IndexFieldNames := 'rom';

  tNes.IndexFieldNames := 'rom';
  tNesMedia.IndexFieldNames := 'rom';
  tNesTGDB.IndexFieldNames := 'rom';
  tNesTGDBImages.IndexFieldNames := 'rom';

end;

procedure Tdm.DataModuleDestroy(Sender: TObject);
begin
  fdconn.Connected := false;
end;

end.
